---
ipmi_hostname: 10.255.71.90
mac_address: 14:02:ec:40:ae:fc
ip_address: 10.253.59.13
subnet: 255.255.255.128
hostname: disstack-wwt-c10.ece.comcast.net
copa_os_sequence_id: 3
serial_number: MXQ61300PB
rack: KAFKA-NX5548-B
model: ProLiant DL360 Gen9
