---
ipmi_hostname: 10.255.71.88
mac_address: 14:02:ec:43:22:40
ip_address: 10.253.59.11
subnet: 255.255.255.128
hostname: disstack-wwt-c8.ece.comcast.net
copa_os_sequence_id: 3
serial_number: MXQ61300M0
rack: KAFKA-NX5548-B
model: ProLiant DL360 Gen9
