---
ipmi_hostname: 10.255.71.68
mac_address: 1c:98:ec:13:10:9c
ip_address: 10.253.59.21
subnet: 255.255.255.128
hostname: disstack-wwt-c18.ece.comcast.net
copa_os_sequence_id: 3
serial_number: MXQ6290859
rack: KAFKA-NX5548-B
model: ProLiant DL380 Gen9
