#! /bin/bash
IP_FILE=$1
OUTPUT_FOLDER=$2

mkdir -p $OUTPUT_FOLDER

for ip in `cat $IP_FILE`
do
    echo "Getting System Information for: ${ip}" 
	sshpass -p $ilo_pass ssh $ilo_user@$ip "show -a " | tee ./$OUTPUT_FOLDER/$ip
done