#!/bin/bash

# The first arg can be an ip or a file with ips in it (one per line)
if [ -f "$1" ]
then
  IP_LIST=`cat $1`
else
  IP_LIST=$1
fi

ISO_URL=$2
for ip in $IP_LIST
do
    echo "ISO Boot on ${ip} to $ISO_URL" 
    sshpass -p $ilo_pass ssh $ilo_user@$ip "power off"
    sshpass -p $ilo_pass ssh $ilo_user@$ip "set /map1/oemhp_vm1/cddr1 oemhp_image=$ISO_URL"
    sshpass -p $ilo_pass ssh $ilo_user@$ip "set /map1/oemhp_vm1/cddr1 oemhp_boot=connect"
    sshpass -p $ilo_pass ssh $ilo_user@$ip "set /map1/oemhp_vm1/cddr1 oemhp_boot=once"
	sshpass -p $ilo_pass ssh $ilo_user@$ip "power on"
done
